kind: Service
apiVersion: v1
metadata:
  name: workshopgi
  namespace: ernst
spec:
  selector:
    app: workshopgi
  type: LoadBalancer
  ports:
    - name: proxy
      port: 80
      targetPort: 5678